urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView

import django_js_reverse.views

from . import views
AJAXurlpatterns = [
    url(r'edit/thread/participant/(?P<thread_pk>[0-9]+)-(?P<pk>[0-9]+)/'
        r'(?P<action>\w+)$', views.RelThreadParticipant.as_view(),
        name="relThreadParticipant"),
]

urlpatterns = [
    url(r'^$', views.HomePageView.as_view(), name='home'),
    url(r'about$', TemplateView.as_view(template_name="sis_main/about.html"),
        name='about'),
    url(r'^jsreverse/$', django_js_reverse.views.urls_js, name='js_reverse'),
    url(r'ajax/', include(AJAXurlpatterns, namespace="ajax_main")),

    url(r'announcements/list$', views.ListAnnouncements.as_view(),
        name='listAnnouncements'),
    url(r'announcements/add$', views.AddAnnouncement.as_view(),
        name="addAnnouncement"),
    url(r'announcements/show/(?P<pk>[0-9]+)$',
        views.DetailAnnouncement.as_view(), name="showAnnouncement"),
    url(r'announcements/delete/(?P<pk>[0-9]+)$',
        views.DeleteAnnouncement.as_view(), name="deleteAnnouncement"),
    url(r'announcements/edit/(?P<pk>[0-9]+)$',
        views.EditAnnouncement.as_view(), name="editAnnouncement"),

    url(r'messages/show/(?P<pk>[0-9]+)$', views.ShowThread.as_view(),
        name="showThread"),
    url(r'messages/list/', views.ListThreads.as_view(),
        name="listThreads"),
    url(r'messages/thread/add$', views.AddThread.as_view(),
        name="addThread"),
    url(r'messages/thread/show/(?P<pk>[0-9]+)$',
        views.ShowThreadMeta.as_view(), name="showThreadMeta"),
    url(r'messages/thread/edit/(?P<pk>[0-9]+)$', views.EditThread.as_view(),
        name="editThread"),
    url(r'messages/thread/delete/(?P<pk>[0-9]+)$',
        views.DeleteThread.as_view(), name="deleteThread"),
              ]

models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from stripped_fields.models.fields import CharFieldStripped, TextFieldStripped
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.utils import IntegrityError
from django.db import transaction


@python_2_unicode_compatible
class Announcement(models.Model):
    """Represents a site-wide announcement shown on home page"""

    text = TextFieldStripped(verbose_name=_("Announcement text"),
                             help_text=_("The text of this announcement"),
                             blank=False, null=False)

    creation_time = models.DateTimeField(auto_now_add=True,
                                         verbose_name=_("Date of Creation"))

    show = models.BooleanField(verbose_name=_("Show"),
                               help_text=_("Should the text be "
                                           "showen to users?"))

    def __str__(self):
        return self.text

    class Meta:  # pylint: disable=old-style-class

        """ Meta information for :py:class:`Announcement` """
        # pylint: disable=too-few-public-methods, no-init
        verbose_name = _('Announcement')
        verbose_name_plural = _('Announcements')


# ################################ Messages ##################################
@python_2_unicode_compatible
class Thread(models.Model):
    """ Thread of conversation"""

    title = CharFieldStripped(verbose_name=_("Title of Thread"),
                              help_text=_("The title of Conversation "
                              "Thread."), blank=False, null=False,
                              max_length=30)

    isLocked = models.BooleanField(verbose_name=_("Thread locked"),
                                   help_text=_("Is the Thread locked, "
                                   "therefore no Messages can be added?"),
                                   default=False)

    createdAt = models.DateTimeField(auto_now_add=True,
                                     verbose_name=_("Date and Time of "
                                                    "Creation"),
                                     help_text=_("Date and Time when the "
                                                 "Thread was created."))

    def __str__(self):
        return self.title

    @property
    def originalPoster(self):
        tmp = self.messages.order_by("createdAt").first()
        if tmp is not None:
            return tmp.participant.user
        else:
            return tmp

    @property
    def lastMessage(self):
        return self.messages.latest('createdAt')

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('showThreadMeta', args=[str(self.pk)])

    class Meta:  # pylint: disable=old-style-class

        """ Meta information for :py:class:`Thread` """
        # pylint: disable=too-few-public-methods, no-init
        verbose_name = _("Thread")
        verbose_name_plural = _("Threads")
        permissions = (('threads_can_see_all',
                        _("Can see all threads.")),)


@python_2_unicode_compatible
class Participant(models.Model):
    """ Participant of Thread """

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("User"),
                             help_text=_("User which is Participant of a "
                                         "Thread."),
                             related_name="participates")

    thread = models.ForeignKey(Thread, verbose_name=_("Thread"),
                               help_text=_("Thread in which User "
                                           "participates."),
                               related_name="participants")

    isAdmin = models.BooleanField(default=False,
                                  verbose_name=_("Administrator"),
                                  help_text=_("Is participant "
                                              "Administrator?"))

    isActive = models.BooleanField(default=True,
                                   verbose_name=_("Is active"),
                                   help_text=_("False when user leaved "
                                               "the Thred."))

    def __str__(self):
        return self.user.get_full_name() + ": " + self.thread.title

    class Meta:  # pylint: disable=old-style-class

        """ Meta information for :py:class:`Participant` """
        # pylint: disable=too-few-public-methods, no-init
        verbose_name = _("Participant")
        verbose_name_plural = _("Participants")
        unique_together = ('user', 'thread')


@python_2_unicode_compatible
class unreadThread(models.Model):
    """ Record that user have unread thread"""

    participant = models.OneToOneField(Participant,
                                       verbose_name=_("Participant"),
                                       help_text=_("Participant in a Thread."),
                                       related_name="unread")

    thread = models.ForeignKey(Thread, verbose_name=_("Thread"),
                               help_text=_("Thread in which Participant"
                                           "participates."),
                               related_name="unreadparticipants")

    def __str__(self):
        return self.participant.user.get_full_name() + ": " + self.thread.title

    class Meta:  # pylint: disable=old-style-class

        """ Meta information for :py:class:`unreadThread` """
        # pylint: disable=too-few-public-methods, no-init
        verbose_name = _("Unread Thread")
        verbose_name_plural = _("Unread Threads")
        unique_together = ("participant", "thread")


@python_2_unicode_compatible
class Message(models.Model):
    """ Message in Thread"""

    participant = models.ForeignKey(Participant, verbose_name=_("Participant"),
                                    related_name="messages",
                                    help_text=_("Author (Participant in "
                                                "Thread) of Message."))

    thread = models.ForeignKey(Thread, verbose_name=_("Thread"),
                               help_text=_("The Thread in which is the "
                                           "message."),
                               related_name="messages")

    createdAt = models.DateTimeField(auto_now_add=True,
                                     verbose_name=_("Date of Creation"),
                                     help_text=_("Date and Time when the "
                                                 "Message was created."))

    title = CharFieldStripped(verbose_name=_("Title of Message"),
                              help_text=_("Short Text title of Message."),
                              blank=True, null=True, max_length=30)

    text = TextFieldStripped(verbose_name=_("Text of message"),
                             help_text=_("MARKDOWN text of message."))

    def __str__(self):
        if self.title is not None and self.title != "":
            return "%s: %s" % (self.thread.title, self.title)
        elif len(self.text) < 21:
            return "%s \"%s\"" % (self.thread.title,  self.text)
        else:
            return "%s \"%s...\"" % (self.thread.title,  self.text[:20])

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return "%s?page=last" % reverse('showThread',
                                        args=[str(self.thread.pk)])

    class Meta:  # pylint: disable=old-style-class

        """ Meta information for :py:class:`Message` """
        # pylint: disable=too-few-public-methods, no-init
        verbose_name = _("Message")
        verbose_name_plural = _("Messages")


@python_2_unicode_compatible
class FileAttachment(models.Model):
    """ File Attachment for Message """

    message = models.ForeignKey(Message, verbose_name=_("Message"),
                                help_text=_("Message to which is the file "
                                            "attached."))

    file = models.FileField(verbose_name=_("File Attachment"),
                            help_text=_("File Attachment of Message"))

    def __str__(self):
        return "%s - %s" % (self.message, self.file)

    class Meta:  # pylint: disable=old-style-class

        """ Meta information for :py:class:`FileAttachment` """
        # pylint: disable=too-few-public-methods, no-init
        verbose_name = _("File Attachment")
        verbose_name_plural = _("File Attachments")

# ################################ signals ###################################

"""
post_save
=========

sender
    The model class.
instance
    The actual instance being saved.
created
    A boolean; True if a new record was created.
raw
    A boolean; True if the model is saved exactly as presented (i.e. when
    loading a fixture). One should not query/modify other records in the
    database as the database might not be in a consistent state yet.
using
    The database alias being used.
update_fields
    The set of fields to update explicitly specified in the save() method.
    None if this argument was not used in the save() call.

"""

"""
# TODO: this does no longer work implement other way?
@receiver(post_save, sender=Thread, weak=False)
def thread_post_save(sender, instance, created, raw, **kwargs):
    # When Thread is created creates new Participant with original_poster user
    if not raw and created:
        p = Participant(user=instance.originalPoster, thread=instance,
                        isAdmin=True)
        p.save()
"""


@receiver(post_save, sender=Message, weak=False)
def message_post_save(sender, instance, created, raw, **kwargs):
    """ When message is created makes the thread unread by participants"""
    if not raw and created:

templates/sis_main/_announcement.html
{% load i18n %}

{% for obj in objs %}
    <div class="alert alert-info" role="alert">
        {{obj}}
        {% if perms.sis_main.delete_announcement %}
          <a href="#" title="{% trans "Delete Announcement" %}" onclick='text="{{obj}}"; DEL("{% url "deleteAnnouncement" obj.pk %}?next={% url 'home' %}", "{% blocktrans %}Are you sure you want to pernamently delete announcement \"" + text +  "\"?{% endblocktrans %}")'>
            <span class="glyphicon glyphicon-trash pull-right remover" aria-hidden="true"></span>
          </a>
        {% endif %}
    </div>
{% endfor %}

templates/sis_main/about.html
{% extends "sis_main/dashboard.html" %}
{% load i18n %}
{% load static %}
{% load cache %}

{% get_current_language as LANGUAGE_CODE %}

{% block title %}{% trans "About" %}{% endblock %}
{% block content %}
<style> .vcenter {
    display: inline-block;
    vertical-align: middle;
    float: none;
} </style>
<h1> {% trans "About" %}</h1>
<p>{% blocktrans %}
 SIS (School Information System) is modern system for school and education. This system was created by
 Filip Dobrovolný in 2015.
{% endblocktrans %}</p>


<h2> {% trans "Used Technology" %}</h2>
<div class="row">
<div class="col-md-1 vcenter"><a href="https://www.djangoproject.com/" alt="Django">
                       <img src="https://www.djangoproject.com/m/img/logos/django-logo-positive.svg" class="img-responsive img-rounded center-block" alt="Django"></a></div>
<div class="col-md-1 vcenter"><a href="https://www.python.org/" alt="Python">
                       <img src="https://www.python.org/static/community_logos/python-powered-h.svg" class="img-responsive img-rounded center-block" alt="Python"></a></div>
<div class="col-md-1 vcenter"><a href="http://getbootstrap.com" alt="Bootstrap">
                       <img src="http://getbootstrap.com/assets/brand/bootstrap-solid.svg" class="img-responsive img-rounded center-block" alt="Bootstrap"></a></div>
<div class="col-md-1 vcenter"><a href="http://www.w3.org/html/logo/" alt="HTML5">
					   <img src="http://www.w3.org/html/logo/downloads/HTML5_Logo.svg" class="img-responsive img-rounded center-block" alt="HTML5"></a></div>
</div>
{% endblock %}

templates/sis_main/listAnnouncements.html
{% extends "sis_main/dashboard.html" %}

{% load i18n %}
{% load cache %}
{% load static %}

{% get_current_language as LANGUAGE_CODE %}

{% block title %}{% trans "List of announcements" %}{% endblock %}

{% block content %}
  <div class="page-header"><h1>{% trans "List of announcements"%} </h1></div>

{% cache 86400 delete_message_announcement LANGUAGE_CODE request.GET.del %}
    {% if request.GET.del %}
      <div class="alert alert-success" role="alert">
        <strong>{% trans "Success" %}:</strong>
        {% trans "Announcement has been successfully deleted." %}
      </div>
    {% endif %}
{% endcache %}


<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>{% trans "Text" %}</th>
      <th>{% trans "Creation time" %}</th>
      <th>{% trans "Shown" %}</th>
      {% if perms.sis_main.delete_announcement %}
        <th class="text-center" >{% trans "Action" %}</th>
      {% endif %}
    </tr>
  </thead>

  <tbody>
    {% for announcement in pagination %}
      <tr>
        <td><a href="{% url "showAnnouncement" announcement.pk %}">{{ announcement.text|truncatechars:100 }}</a></td>
        <td><a href="{% url "showAnnouncement" announcement.pk %}">{{ announcement.creation_time }}</a></td>
        <td><a href="#" id="shower" data-value="{{ announcement.show|yesno:"1,0" }}" data-type="select" data-url="{% url "editAnnouncement" announcement.pk %}" class="shower" ></a></td>
        {% if perms.sis_main.delete_announcement %}
          <td class="text-center">
            <a href="#" onClick="DEL('{% url "deleteAnnouncement" announcement.pk %}')" title="{% trans "Delete Announcement" %}">
              <span class="glyphicon glyphicon-trash text-danger" aria-hidden="true"></span>
            </a>
          </td>
        {% endif %}
      </tr>
    {% endfor %}
  </tbody>
</table>

{% if pagination.has_other_pages %}{% include "sis_tools/paginator.html" %}{% endif %}

{% if perms.sis_main.add_announcement %}
  <a href="#" class="btn btn-primary" onClick="bootbox.prompt('{% trans "Enter text of Announcement:"%}', addAnnouncementBootboxCallback);">
    <span class="glyphicon glyphicon-plus icon-white" aria-hidden="true"></span>
    {% trans "Add Announcement" %}
  </a>
{% endif %}

{% endblock %}
{% block scripts %}
<script src="{% static "sis_users/tools.js"%}"></script>
<script>
  $.djangocsrf("enable");
  function addAnnouncementBootboxCallback (result) {
    if (result !== null){
       	$.post('{% url "addAnnouncement" %}', { text : result }, addAnnouncementAJAXcallback);
    }
  }
  function addAnnouncementAJAXcallback (resp, status){
    if (status == 'success') {
       	window.location.href = "{% url "showAnnouncement" 0 %}" + resp.ID;
    } else {
       	bootbox.alert("{% trans "ERROR: Can't add Announcement. error: " %}" + resp);
    }
  }

  function DEL(url){
    bootbox.confirm({% blocktrans %}"Are you sure you want to delete this announcement?"{% endblocktrans %}, function(result) {
      if (result) {
        window.location.href = url;
      }
    });
  }
 $(document).ready(function() {
    $('.shower').editable({
        pk: 1,
        source: [
              {value: 0, text: '{% trans "Hidden" %}'},
              {value: 1, text: '{% trans "Shown" %}'},
           ]
    });
});

</script>
{% endblock %}

templates/sis_main/listThreads.html
{% extends "sis_main/dashboard.html" %}

{% load i18n %}
{% load cache %}
{% load static %}

{% get_current_language as LANGUAGE_CODE %}

{% block title %}{% trans "Messages" %}{% endblock %}

{% block content %}
<div class="page-header"><h1>{% trans "Messages"%} </h1></div>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>{% trans "Title" %}</th>
      <th>{% trans "Created" %}</th>
      <th>{% trans "Last Message" %}</th>
      <th class="text-center" >{% trans "Action" %}</th>
    </tr>
  </thead>

  <tbody>
    {% if participant %}
      {% for part in pagination %}
        {% with thread=part.thread lastMessage=part.thread.lastMessage%}
        <tr class="{% if thread.isLocked %}warning{% endif %}">
          <td><a href="{% url "showThread" thread.pk %}?page=1">{{ thread.title }}</a></td>
          {% cache 86400 thread__original_poster thread.pk LANGUAGE_CODE %}
          <td>{% with originalPoster=thread.originalPoster %}
            {% if originalPoster != None %}
            <a href="{% url "showUser" originalPoster.pk %}">
            {{ originalPoster.info.full_name }}</a>
             - {{ thread.createdAt|date:"SHORT_DATE_FORMAT" }}
             {% endif %}
            {% endwith %}
          </td>
          {% endcache %}
          <td {% with unread=part.unread%}{% if unread %}class="info"{% endif %}>
            {% if unread %}<strong>{% trans "NEW"%}:</strong>{% endif %}{% endwith %}
              {% with lastMessageUser=lastMessage.participant.user%}
              <a href="{% url "showUser" lastMessageUser.pk %}"> {{ lastMessageUser.info.full_name }}</a> -
              {% endwith %}
              <a href="{% url "showThread" thread.pk %}">
                {{ lastMessage.createdAt|date:"SHORT_DATETIME_FORMAT" }}
                  {% if part.thread.lastMessage.title %}
                    {{ lastMessage.title }}
                  {% else %}
                    {{ lastMessage.text|truncatechars:30 }}
                  {% endif %}</a>
          </td>
          <td class="text-center">
            <a href="#" title="{% trans "Leave Thread" %}" onClick="DEL_leave('{% url "ajax_main:relThreadParticipant" thread.pk part.pk "remove" %}', '{{ thread.title }}')">
              <span class="glyphicon glyphicon-minus text-danger" aria-hidden="true"></span>
            </a>
            {% if part.isAdmin or perms.sis_main.change_thread %}
              <a href="{% url "showThreadMeta" thread.pk %}" title="{% trans "Edit Thread" %}">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
            {% endif %}
          {% if perms.sis_main.delete_thread %}
              <a href="#" title="{% trans "Delete Thread" %}" onClick="DEL_delete('{% url "deleteThread" thread.pk %}', '{{ thread.title }}')">
                <span class="glyphicon glyphicon-trash text-danger" aria-hidden="true"></span>
              </a>
          {% endif %}
          </td>
        </tr>
        {% endwith %}
      {% endfor %}

    {% else %}
      {% for thread in pagination %}
        <tr class="{% if thread.isLocked %}warning{% endif %}">
          <td><a href="{% url "showThread" thread.pk %}?page=1">{{ thread.title }}</a></td>
          <td>{% if thread.originalPoster %}
            <a href="{% url "showUser" thread.originalPoster.pk %}">
              {{ thread.originalPoster.info.full_name }}
            </a>
             - {{ thread.createdAt|date:"SHORT_DATE_FORMAT" }}{% endif %}
          </td>
          <td><a href="{% url "showThread" thread.pk %}">
            {{ thread.lastMessage.participant.info.full_name }}
            {{ thread.lastMessage.createdAt|date:"SHORT_DATETIME_FORMAT" }}
            {% if part.thread.lastMessage.title %}
              {{ thread.lastMessage.title }}
            {% else %}
              {{ thread.lastMessage.text|truncatechars:30 }}
            {% endif %}</a>
          </td>
          <td class="text-center">
            {% if perms.sis_main.change_thread %}
              <a href="{% url "showThreadMeta" thread.pk %}" title="{% trans "Edit Thread" %}">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
            {% endif %}
            {% if perms.sis_main.delete_thread %}
              <a href="#" title="{% trans "Delete Thread" %}" onClick="DEL_delete('{% url "deleteThread" thread.pk %}', '{{ thread.title }}')">
                <span class="glyphicon glyphicon-trash text-danger" aria-hidden="true"></span>
              </a>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    {% endif %}
  </tbody>
</table>

{% if pagination.has_other_pages %}{% include "sis_tools/paginator.html" %}{% endif %}

{% if perms.sis_main.add_thread %}
  <a href="{% url "addThread" %}" class="btn btn-primary">
    <span class="glyphicon glyphicon-plus icon-white" aria-hidden="true"></span>
    {% trans "Add Thread" %}
  </a>
{% endif %}

{% if perms.sis_main.change_thread or perms.sis_main.delete_thread %}
  {% if participant %}
    <a href="{% url "listThreads" %}?all=true" class="btn btn-primary">
      <span class="glyphicon glyphicon-align-justify icon-white" aria-hidden="true"></span>
      {% trans "Show All" %}
    </a>
  {% else %}
    <a href="{% url "listThreads" %}" class="btn btn-primary">
      <span class="glyphicon glyphicon-inbox icon-white" aria-hidden="true"></span>
      {% trans "Show my Threads" %}
    </a>
  {% endif %}
{% endif %}
{% endblock %}
{% block scripts %}
<script src="{% static "sis_users/tools.js"%}"></script>
<script>
  function DEL_delete(url, name) { DEL(url, {% blocktrans %}"Are you sure you want to delete thread \"" + name +  "\"?"{% endblocktrans %})}
  function DEL_leave(url, name) { DEL(url, {% blocktrans %}"Are you sure you want to leave thread \"" + name +  "\"?"{% endblocktrans %})}
</script>
{% endblock %}

templates/sis_main/nav.html
{% load i18n %}
{% load cache%}
{% load messages %}

{% get_current_language as LANGUAGE_CODE %}

{% comment %}
   Navigace - aktivace jednotlive skupiny pomoci tridy "in"
   Skupina - aktivace pomoci tridy "info"
   var active - otevření jednotlivé skupiny ID od 0
   var subactive - podbarvení jednotlivé položky ve skupině ID od 0 (v rámci třídy)
{% endcomment %}

{% cache 30 sidemenu LANGUAGE_CODE request.user.pk active subactive %}
  <div class="panel-group" id="accordion">

    {# Uvodni panel #}
    {% cache 86400 sidemenu_main active subactive LANGUAGE_CODE %}
      <div class="panel {% if active == 0 %} panel-primary {% else %} panel-default {% endif %}">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
             <span class="glyphicon glyphicon-folder-close"></span>
             {% trans "Main" %}
            </a>
          </h4>
        </div>

        <div id="collapseOne" class="panel-collapse collapse {% if active == 0 %} in {% endif %}">
          <div class="panel-body">
            <table class="table">
              <tr>
                <td {% if active == 0 and subactive == 0 %}class="info"{% endif %}>
                  <span class="glyphicon glyphicon-pencil text-primary"></span>
                  <a href="{% url "home" %}">{% trans "Main Page"%}</a>
                </td>
             </tr>
    {% endcache %}
             <tr>
               <td {% if active == 0 and subactive == 2 %}class="info"{% endif %}>
                 <span class="glyphicon glyphicon-envelope text-primary"></span>
                 {% count_unread_messages as num %}
                 <a href="{% url "listThreads" %}">{% trans "Messages"%}{% if num > 0 %} <span class="badge">{{num}}</span>{% endif %}</a>
               </td>
            </tr>
              {% if perms.sis_main.add_announcement or perms.sis_main.edit_announcement or perms.sis_main.change_announcement %}
                <tr>
                  <td {% if active == 0 and subactive == 1 %}class="info"{% endif %}>
                    <span class="glyphicon glyphicon-bullhorn text-primary"></span>
                    <a href="{% url "listAnnouncements" %}">{% trans "Announcements"%}</a>
                  </td>
                </tr>
              {% endif %}
              {% if request.user.is_staff %}
                <tr>
                  <td>
                    <span class="glyphicon glyphicon-equalizer text-primary"></span>
                    <a href="{% url "admin:index" %}">{% trans "Admin Site"%}</a>
                  </td>
                </tr>
              {% endif %}
            </table>
          </div>
        </div>
      </div>



    {# TADY PRIDAVAT OSTATNI MODULY #}

    {% include "sis_users/nav.html" %}

    {% include "sis_classes/nav.html" %}
    
    {% include "sis_grades/nav.html" %}

  </div>
{% endcache %}

templates/sis_main/showAnnouncement.html
{% extends "sis_main/dashboard.html" %}

{% load i18n %}
{% load cache %}
{% load static %}

{% get_current_language as LANGUAGE_CODE %}

{% block title %}{% trans "Announcement" %}: {{ obj.text|truncatechars:20 }}{% endblock %}

{% block content %}
 <div class="page-header"><h1>{% trans "Announcement" %}: {{ obj.text|truncatechars:25 }}</h1></div>

 <table class="table">
   <tbody>
     <tr>
       <td>{% trans "Text" %}:</td>
       <td>{% if perms.sis_main.edit_announcement %}
             <a href="#" id="name" data-type="text" data-pk="1" data-emptytext="{% trans "Empty" %}" data-url="{% url "editAnnouncement" obj.pk %}" data-title="{% trans "Text"%}">{{ obj.text }}</a>
           {% else %}{{ obj.text }}{% endif %}</td>
     </tr>
     <tr>
       <td>{% trans "Creation time" %}:</td>
       <td>{{ obj.creation_time|date:"DATETIME_FORMAT" }}</td>
     </tr>
     <tr>
        <td>{% trans "Shown" %}:</td>
        <td>
            <a href="#" id="shower" data-value="{{ obj.show|yesno:"1,0" }}" data-type="select" data-url="{% url "editAnnouncement" obj.pk %}" class="shower" ></a>
        </td>
     </tr>
   </tbody>
 </table>

 {% if perms.sis_main.delete_announcement %}
  <button type="button" class="btn btn-danger" onClick="DEL_Annoucement('{% url "deleteAnnouncement" obj.id %}',  '{{ obj.text|truncatechars:50 }}')" >
    <span class="glyphicon glyphicon-trash icon-white" aria-hidden="true"></span>
    {% trans "Delete" %}
  </button>
 {% endif %}
{% endblock %}
{% block scripts %}
<script src="{% static "sis_users/tools.js"%}"></script>
<script>
  $.djangocsrf( "enable" );
  function DEL_Annoucement(url, name) { DEL(url, {% blocktrans %}"Are you sure you want to delete \"" + name +  "\" ?"{% endblocktrans %})}
  $(document).ready(function() {
    $('.shower').editable({
        pk: 1,
        source: [
              {value: 0, text: '{% trans "Hidden" %}'},
              {value: 1, text: '{% trans "Shown" %}'},
           ]
    });
    $('#name').editable();
});
</script>
{% endblock %}